/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface UserProfile {
  'isTrusted' : boolean,
  'adPin' : [] | [string],
  'estimatedEarnings' : number,
  'displayName' : string,
  'secretUsername' : string,
  'isPremium' : boolean,
  'name' : string,
  'monetizationPlan' : [] | [string],
  'totalEarnings' : number,
  'isMonetized' : boolean,
  'cpmRank' : [] | [string],
  'subscriberCount' : bigint,
  'paypalEmail' : [] | [string],
  'strikes' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoContent {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'code' : Uint8Array,
  'description' : string,
  'availability' : boolean,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  /**
   * / CRUD interface for user profiles (REQUIRED)
   */
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'getAccessLevel' : ActorMethod<[], string>,
  'getAllVideos' : ActorMethod<[], Array<VideoContent>>,
  /**
   * / CRUD interface for user profiles (REQUIRED)
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Users can access their own or admin profiles only
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPurchasedVideos' : ActorMethod<[Principal], Array<VideoContent>>,
  'getVideosByPriceRange' : ActorMethod<[bigint, bigint], Array<VideoContent>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseVideos' : ActorMethod<[Array<bigint>], undefined>,
  /**
   * / Any registered user can save their own profile (user or admin)
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadVideo' : ActorMethod<[string, string, Uint8Array, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];